version: "3"

services:
  brew-next-app:
    container_name: brew-next-app
    build:
      context: .
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    # env_file:
      # - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    networks:
      - brew-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  brew-network:
    external: true